/* data.js — Dữ liệu mẫu (Mock data units & statuses) cho Báo cáo Thống kê */
const STATUSES = ['Chờ phân công', 'Đang xử lý', 'Đã có báo cáo', 'Chờ phê duyệt', 'Đã kết thúc'];

const UNITS = [
  'Sở Thông tin và Truyền thông',
  'Công an Tỉnh Gia Lai',
  'Sở Tài nguyên và Môi trường',
  'Sở Lao động - Thương binh và Xã hội',
  'Sở Giáo dục và Đào tạo',
  'Sở Y tế',
  'Ban Dân tộc Tỉnh Gia Lai',
  'Sở Khoa học và Công nghệ',
  'Sở Kế hoạch và Đầu tư',
  'Sở Tài chính',
  'Sở Nội vụ',
  'Sở Tư pháp',
  'Sở Công Thương',
  'Sở Xây dựng',
  'Sở Giao thông Vận tải',
  'Sở Văn hóa, Thể thao và Du lịch',
  'Sở Nông nghiệp và Phát triển nông thôn',
  'Thanh tra Tỉnh',
  'Văn phòng UBND Tỉnh',
  'Ban Quản lý Khu kinh tế',
  'Chi cục Thủy lợi',
  'Chi cục Trồng trọt và Bảo vệ thực vật',
  'Chi cục Chăn nuôi và Thú y',
  'Chi cục Kiểm lâm',
  'Trung tâm Kiểm soát bệnh tật tỉnh',
  'Trung tâm Y tế thành phố Pleiku',
  'Trung tâm Y tế huyện Chư Păh',
  'Trung tâm Y tế huyện Chư Prông',
  'Đài Phát thanh – Truyền hình Gia Lai',
  'Báo Gia Lai',
  'Hội Liên hiệp Phụ nữ Tỉnh',
  'Đoàn Thanh niên Cộng sản Hồ Chí Minh Tỉnh',
  'Liên đoàn Lao động Tỉnh',
  'Ban Quản lý rừng phòng hộ Bắc Gia Lai',
  'Ban Quản lý rừng phòng hộ Nam Gia Lai',
  'UBND thành phố Pleiku',
  'UBND thị xã An Khê',
  'UBND thị xã Ayun Pa',
  'UBND huyện Chư Păh',
  'UBND huyện Chư Prông',
  'UBND huyện Chư Sê',
  'UBND huyện Đăk Đoa',
  'UBND huyện Đăk Pơ',
  'UBND huyện Đức Cơ',
  'UBND huyện Ia Grai',
  'UBND huyện Ia Pa',
  'UBND huyện KBang',
  'UBND huyện Kông Chro',
  'UBND huyện Krông Pa',
  'UBND huyện Mang Yang',
  'UBND huyện Phú Thiện',
  'UBND huyện Chư Pưh',
  'Phòng Tài chính – Kế hoạch thành phố Pleiku'
];
