#!/usr/bin/env node
/**
 * Quét pages/* → sinh shared/js/routes.js
 * HTML root mỗi folder: index.html → admin.html → *.html đầu tiên (root folder).
 * Bỏ qua folder "home".
 *
 * Chạy: node tools/generate-routes.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'pages');
const OUT_FILE = path.join(ROOT, 'shared', 'js', 'routes.js');
const SKIP = new Set(['home']);
const ROOT_HTML_PRIORITY = ['index.html', 'admin.html'];

function findRootHtml(dir) {
  const names = fs.readdirSync(dir);
  for (const preferred of ROOT_HTML_PRIORITY) {
    if (names.includes(preferred) && fs.statSync(path.join(dir, preferred)).isFile()) {
      return preferred;
    }
  }
  const htmlFiles = names
    .filter((n) => n.toLowerCase().endsWith('.html'))
    .filter((n) => fs.statSync(path.join(dir, n)).isFile())
    .sort((a, b) => a.localeCompare(b, 'vi'));
  return htmlFiles[0] || null;
}

function toId(folderName) {
  return folderName
    .normalize('NFC')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-À-ỹ]/gi, '');
}

function scan() {
  if (!fs.existsSync(PAGES_DIR)) {
    throw new Error(`Không tìm thấy: ${PAGES_DIR}`);
  }

  const entries = fs.readdirSync(PAGES_DIR, { withFileTypes: true });
  const routes = [];

  for (const ent of entries) {
    if (!ent.isDirectory()) continue;
    if (SKIP.has(ent.name.toLowerCase())) continue;

    const folder = ent.name;
    const dir = path.join(PAGES_DIR, folder);
    const html = findRootHtml(dir);
    if (!html) {
      console.warn(`[skip] ${folder}: không có HTML root`);
      continue;
    }

    // Relative từ pages/home/; encode từng segment (Unicode / khoảng trắng)
    const encFolder = encodeURIComponent(folder);
    const encHtml = encodeURIComponent(html);
    const relFromHome = `../${encFolder}/${encHtml}`;
    routes.push({
      id: toId(folder) || folder,
      title: folder,
      path: relFromHome,
      folder,
      html,
    });
  }

  routes.sort((a, b) => a.title.localeCompare(b.title, 'vi'));
  return routes;
}

function writeRoutes(routes) {
  const outDir = path.dirname(OUT_FILE);
  fs.mkdirSync(outDir, { recursive: true });

  const body = JSON.stringify(routes, null, 2);
  const content = `/* AUTO-GENERATED by tools/generate-routes.js — không sửa tay */
window.GIALAI_ROUTES = ${body};
`;
  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log(`Đã ghi ${routes.length} route → ${path.relative(ROOT, OUT_FILE)}`);
  routes.forEach((r) => console.log(`  - ${r.title} → ${r.path}`));
}

writeRoutes(scan());
