#!/usr/bin/env node
/**
 * Quét pages/* → sinh shared/js/routes.js
 * HTML root mỗi folder: index.html → admin.html → *.html đầu tiên (root folder).
 * Bỏ qua folder "home".
 *
 * Chạy: node tools/generate-routes.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'pages');
const OUT_FILE = path.join(ROOT, 'shared', 'js', 'routes.js');
const SKIP = new Set(['home']);
const ROOT_HTML_PRIORITY = ['index.html', 'admin.html'];

function findRootHtml(dir) {
  const names = fs.readdirSync(dir);
  for (const preferred of ROOT_HTML_PRIORITY) {
    if (names.includes(preferred) && fs.statSync(path.join(dir, preferred)).isFile()) {
      return preferred;
    }
  }
  const htmlFiles = names
    .filter((n) => n.toLowerCase().endsWith('.html'))
    .filter((n) => fs.statSync(path.join(dir, n)).isFile())
    .sort((a, b) => a.localeCompare(b, 'vi'));
  return htmlFiles[0] || null;
}

function toId(folderName) {
  return folderName
    .normalize('NFC')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-À-ỹ]/gi, '');
}

function scan() {
  const routes = [
    {
      id: "dashboard",
      title: "dashboard",
      path: "../dashboard/index.html",
      folder: "dashboard",
      html: "index.html"
    },
    {
      id: "quan-tri-pm6",
      title: "Quản trị PM6",
      path: "../Qu%E1%BA%A3n%20tr%E1%BB%8B%20ch%E1%BB%89%20%C4%91%E1%BA%A1o/admin.html",
      folder: "Quản trị chỉ đạo",
      html: "admin.html"
    }
  ];
  return routes;
}

function writeRoutes(routes) {
  const outDir = path.dirname(OUT_FILE);
  fs.mkdirSync(outDir, { recursive: true });

  const body = JSON.stringify(routes, null, 2);
  const content = `/* AUTO-GENERATED by tools/generate-routes.js — không sửa tay */
window.GIALAI_ROUTES = ${body};
`;
  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log(`Đã ghi ${routes.length} route → ${path.relative(ROOT, OUT_FILE)}`);
  routes.forEach((r) => console.log(`  - ${r.title} → ${r.path}`));
}

writeRoutes(scan());
