/* AUTO-GENERATED by tools/generate-routes.js — không sửa tay */
window.GIALAI_ROUTES = [
  {
    "id": "dashboard",
    "title": "dashboard",
    "path": "../dashboard/index.html",
    "folder": "dashboard",
    "html": "index.html"
  },
  {
    "id": "iam",
    "title": "IAM",
    "path": "../IAM/index.html",
    "folder": "IAM",
    "html": "index.html"
  },
  {
    "id": "quản-trị",
    "title": "Quản trị",
    "path": "../Qu%E1%BA%A3n%20tr%E1%BB%8B/admin.html",
    "folder": "Quản trị",
    "html": "admin.html"
  }
];
